library(randomForest)
indeedTrain = read.csv("indeedTrain.csv")
indeedTest = read.csv("indeedTest.csv")

Log1 = randomForest(Part ~ ., data=indeedTrain, family = binomial)
Log2 = randomForest(Full ~ ., data=indeedTrain, family = binomial)
Log3 = randomForest(Salary ~ ., data=indeedTrain, family = binomial)
Log4 = randomForest(Hourly ~ ., data=indeedTrain, family = binomial)
Log5 = randomForest(Licence ~ ., data=indeedTrain, family = binomial)
Log6 = randomForest(Bsdegree ~ ., data=indeedTrain, family = binomial)
Log7 = randomForest(Ms_or_phd ~ ., data=indeedTrain, family = binomial)
Log8 = randomForest(Associate ~ ., data=indeedTrain, family = binomial)
Log9 = randomForest(OneYear ~ ., data=indeedTrain, family = binomial)
Log10 = randomForest(TwoYears ~ ., data=indeedTrain, family = binomial)
Log11 = randomForest(FiveYears ~ ., data=indeedTrain, family = binomial)
Log12 = randomForest(Supervising ~ ., data=indeedTrain, family = binomial)

Log1Prediction = predict(Log1, newdata = indeedTest, type="response")
Log2Prediction = predict(Log2, newdata = indeedTest, type="response")
Log3Prediction = predict(Log3, newdata = indeedTest, type="response")
Log4Prediction = predict(Log4, newdata = indeedTest, type="response")
Log5Prediction = predict(Log5, newdata = indeedTest, type="response")
Log6Prediction = predict(Log6, newdata = indeedTest, type="response")
Log7Prediction = predict(Log7, newdata = indeedTest, type="response")
Log8Prediction = predict(Log8, newdata = indeedTest, type="response")
Log9Prediction = predict(Log9, newdata = indeedTest, type="response")
Log10Prediction = predict(Log10, newdata = indeedTest, type="response")
Log11rediction = predict(Log11, newdata = indeedTest, type="response")
Log12Prediction = predict(Log12, newdata = indeedTest, type="response")

sum(diag(table(indeedTest$Part, Log1Prediction >= 0.5)))/nrow(test)
sum(diag(table(indeedTest$Full, Log2Prediction >= 0.5)))/nrow(test)
sum(diag(table(indeedTest$Salary, Log3Prediction >= 0.5)))/nrow(test)
sum(diag(table(indeedTest$Hourly, Log4Prediction >= 0.5)))/nrow(test)
sum(diag(table(indeedTest$Licence, Log5Prediction >= 0.5)))/nrow(test)
sum(diag(table(indeedTest$Bsdegree, Log6Prediction >= 0.5)))/nrow(test)
sum(diag(table(indeedTest$Ms_or_phd, Log7Prediction >= 0.5)))/nrow(test)
sum(diag(table(indeedTest$Associate, Log8Prediction >= 0.5)))/nrow(test)
sum(diag(table(indeedTest$OneYear, Log9Prediction >= 0.5)))/nrow(test)
sum(diag(table(indeedTest$TwoYears, Log10Prediction >= 0.5)))/nrow(test)
sum(diag(table(indeedTest$FiveYears, Log11Prediction >= 0.5)))/nrow(test)
sum(diag(table(indeedTest$Supervising, Log12Prediction >= 0.5)))/nrow(test)
